plugin_message_prefix: "[HumbleVote]"
debug: true

votes:
  # face votes are used mostly for development purposes, and should  be FALSE in production server
  fake_votes: false
  # Number of months back to keep records for players
  monthly_history: 12
  # Timezone for voting statistics and rewards
  # Available options are https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timezone_id: "UTC"

  vote_notification:
    queued_broadcast: true
    queued_broadcast_wait_time: 200 # Ticks (20 ticks == 1 second)
    broadcast_message: "► {player} has voted {x} times for rewards"
  vote_reminder:
      enabled: true
      message: "&8Remember to vote for our server with &6/hvote&8 voting"
      on_join: true
      repeat: 180 # Seconds
      # disable the reminder for users that have already voted on all the sites
      disable_on_all_votes: true


sql:
  # SQLite, MySQL are supported databases
  driver: SQLite
  # Database server address.
  address: localhost:3306
  # Database name, username and password.
  database: 'humblevote'
  username: ''
  password: ''
  table_prefix: 'humblevote_'
  # ...interval in seconds, when the database should be pinged,
  # to keep the connection alive
  # You can set this to '0' to disable the ping interval
  ping_interval: 3600
  # Database engine. Only applies to MySQL.
  engine: InnoDB

  options: 'useSSL=false&serverTimezone=UTC'


# This is only used for development and testing !
# TOUCHABLE ONLY BY THE DEVELOPERS
development:
  enabled: false
  # Change the year|month for monthly voting statistics
  year: 2015
  month: 11
  day: 1
  hour: 0
  minute: 0
  zoneOffset: "+00:00"
