name: HumbleVote
version: ${project.version}
main: com.pustinek.humblevote.Main
api-version: "1.13"
authors: [Pustinek]
depend: [Votifier]
softdepend: [PlaceholderAPI]
description: "Voting plugin for minecraft"
commands:
  humblevote:
    description: 'for all the commands use /HumbleVote help'
    usage: 'change_me_plugin_name has not started correctly, check the log file (or console) and correct any errors.'
    aliases: []
permissions:
  humblevote.*:
    description: 'Give access to all commands of McTemplate'
    default: op
    children:
      humblevote.reload: true
  humblevote.reload:
    description: 'reload plugin config files'
    default: op